### ISSUE TITLE
Save Scene after opening Owned Scene UUID

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#247]
As a user opening a pre-existing 3dstreet scene saved in firestore database, and if I am the author of this scene, when I click the cloud Save button I should be saving the JSON file to the existing scene UUID instead of saving as a new scene UUID.

Saving a scene in this manner should update the [updateTimestamp](https://github.com/3DStreet/3dstreet-editor/issues/248)

**Comment by kfarr** [comment]
@ViktoriaShurhot @rostyslavnahornyi I also don't see a PR for this

**Comment by ViktoriaShurhot** [comment]
@kfarr  sorry, we fixed it

**Comment by kfarr** [comment]
Hi @ViktoriaShurhot I still don't see a PR for this ticket, unless https://github.com/3DStreet/3dstreet-editor/pull/273/files also includes this ticket?

**Comment by kfarr** [comment]
Yes it looks like that PR addresses both this ticket #247 and #248

**Comment by kfarr** [comment]
closed by #274 however there still a bug where some scenes that are loaded that I own will not save but do save as instead. To be tracked as new issue #275
